# image:
#   repository: registry

# service:
#   type: ClusterIP
#   port: 5000

# storage: filesystem

secrets:
  htpasswd: "dewep:$2y$05$/sj0flN17lfOmZyejCODAe8OkNtD8CuhGMaAy2sC9ZQL25qnNHQ1."

ingress:
  enabled: true
  hosts:
    - registry.k8s.dewep.net
  annotations:
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "30720m"
  tls:
    - secretName: docker-registry-prod
      hosts:
        - registry.k8s.dewep.net
