apiVersion: v1
kind: Service
metadata:
  name: hello-argjolan
spec:
  type: ClusterIP
  selector:
    app: hello-argjolan
  ports:
    - protocol: "TCP"
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-argjolan-deployment
  labels:
    app: hello-argjolan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-argjolan
  template:
    metadata:
      labels:
        app: hello-argjolan
    spec:
      containers:
        - name: hello-argjolan
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: hello-argjolan-configs
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: hello-argjolan-configs
          configMap:
            name: hello-argjolan-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-argjolan-config
data:
  default.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name  _;

      location / {
        add_header Content-Type text/plain;
        return 200 "Hello ArGJolan!";
      }
    }
